// svelte/src/lib/Navigation.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';

	function isActive(path: string): boolean {
		return $page.url.pathname === path;
	}
</script>

<nav class="bg-white shadow-lg">
	<div class="container mx-auto px-4">
		<div class="flex justify-between items-center h-16">
			<div class="flex items-center">
				<a href="/" class="text-xl font-bold text-gray-900 hover:text-blue-600 transition-colors">
					Svelte App
				</a>
			</div>
			
			<div class="hidden md:flex space-x-8">
				<a
					href="/"
					class="px-3 py-2 rounded-md text-sm font-medium transition-colors {isActive('/') 
						? 'text-blue-600 bg-blue-50' 
						: 'text-gray-700 hover:text-blue-600 hover:bg-gray-50'}"
				>
					Home
				</a>
				<a
					href="/about"
					class="px-3 py-2 rounded-md text-sm font-medium transition-colors {isActive('/about') 
						? 'text-blue-600 bg-blue-50' 
						: 'text-gray-700 hover:text-blue-600 hover:bg-gray-50'}"
				>
					About
				</a>
				<a
					href="/contact"
					class="px-3 py-2 rounded-md text-sm font-medium transition-colors {isActive('/contact') 
						? 'text-blue-600 bg-blue-50' 
						: 'text-gray-700 hover:text-blue-600 hover:bg-gray-50'}"
				>
					Contact
				</a>
			</div>
			
			<!-- Mobile menu button -->
			<div class="md:hidden">
				<button class="text-gray-700 hover:text-blue-600 focus:outline-none focus:text-blue-600">
					<svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
					</svg>
				</button>
			</div>
		</div>
	</div>
</nav>

// nextjs/src/components/Navigation.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function Navigation() {
  const pathname = usePathname();

  const isActive = (path: string) => {
    return pathname === path;
  };

  return (
    <nav className="bg-white shadow-lg">
      <div className="container mx-auto px-4">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center">
            <Link href="/" className="text-xl font-bold text-gray-900 hover:text-blue-600 transition-colors">
              Next.js App
            </Link>
          </div>
          
          <div className="hidden md:flex space-x-8">
            <Link
              href="/"
              className={`px-3 py-2 rounded-md text-sm font-medium transition-colors ${
                isActive('/') 
                  ? 'text-blue-600 bg-blue-50' 
                  : 'text-gray-700 hover:text-blue-600 hover:bg-gray-50'
              }`}
            >
              Home
            </Link>
            <Link
              href="/about"
              className={`px-3 py-2 rounded-md text-sm font-medium transition-colors ${
                isActive('/about') 
                  ? 'text-blue-600 bg-blue-50' 
                  : 'text-gray-700 hover:text-blue-600 hover:bg-gray-50'
              }`}
            >
              About
            </Link>
            <Link
              href="/contact"
              className={`px-3 py-2 rounded-md text-sm font-medium transition-colors ${
                isActive('/contact') 
                  ? 'text-blue-600 bg-blue-50' 
                  : 'text-gray-700 hover:text-blue-600 hover:bg-gray-50'
              }`}
            >
              Contact
            </Link>
          </div>
          
          {/* Mobile menu button */}
          <div className="md:hidden">
            <button className="text-gray-700 hover:text-blue-600 focus:outline-none focus:text-blue-600">
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
}
