// react-vite/src/pages/About.tsx
import React from 'react';

const About: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-emerald-100">
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold text-gray-900 mb-4">About Us</h1>
            <p className="text-xl text-gray-600">
              Learn more about our mission and the technology behind this application.
            </p>
          </div>
          
          <div className="bg-white rounded-lg shadow-lg p-8 mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Our Mission</h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              We're passionate about creating modern, performant web applications that provide 
              exceptional user experiences. This project demonstrates the power of combining 
              React, TypeScript, Vite, and Tailwind CSS to build beautiful, scalable applications.
            </p>
            <p className="text-gray-700 leading-relaxed">
              Our goal is to showcase best practices in modern web development while providing 
              a solid foundation for building real-world applications.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="bg-white rounded-lg shadow-lg p-6">
              <h3 className="text-xl font-semibold text-gray-900 mb-4">Technology Stack</h3>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>
                  React 18 with TypeScript
                </li>
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-green-500 rounded-full mr-3"></span>
                  Vite for fast development
                </li>
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-purple-500 rounded-full mr-3"></span>
                  Tailwind CSS for styling
                </li>
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-orange-500 rounded-full mr-3"></span>
                  React Router for navigation
                </li>
              </ul>
            </div>
            
            <div className="bg-white rounded-lg shadow-lg p-6">
              <h3 className="text-xl font-semibold text-gray-900 mb-4">Features</h3>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>
                  Multi-page navigation
                </li>
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-green-500 rounded-full mr-3"></span>
                  Responsive design
                </li>
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-purple-500 rounded-full mr-3"></span>
                  Type-safe development
                </li>
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-orange-500 rounded-full mr-3"></span>
                  Modern UI components
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;

// svelte/src/routes/about/+page.svelte
<div class="min-h-screen bg-gradient-to-br from-green-50 to-emerald-100">
	<div class="container mx-auto px-4 py-16">
		<div class="max-w-4xl mx-auto">
			<div class="text-center mb-12">
				<h1 class="text-4xl font-bold text-gray-900 mb-4">About Us</h1>
				<p class="text-xl text-gray-600">
					Learn more about our mission and the technology behind this application.
				</p>
			</div>
			
			<div class="bg-white rounded-lg shadow-lg p-8 mb-8">
				<h2 class="text-2xl font-semibold text-gray-900 mb-4">Our Mission</h2>
				<p class="text-gray-700 leading-relaxed mb-6">
					We're passionate about creating modern, performant web applications that provide 
					exceptional user experiences. This project demonstrates the power of combining 
					Svelte, TypeScript, and Tailwind CSS to build beautiful, scalable applications.
				</p>
				<p class="text-gray-700 leading-relaxed">
					Our goal is to showcase best practices in modern web development while providing 
					a solid foundation for building real-world applications.
				</p>
			</div>
			
			<div class="grid grid-cols-1 md:grid-cols-2 gap-8">
				<div class="bg-white rounded-lg shadow-lg p-6">
					<h3 class="text-xl font-semibold text-gray-900 mb-4">Technology Stack</h3>
					<ul class="space-y-2 text-gray-700">
						<li class="flex items-center">
							<span class="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>
							Svelte 5 with TypeScript
						</li>
						<li class="flex items-center">
							<span class="w-2 h-2 bg-green-500 rounded-full mr-3"></span>
							SvelteKit for routing
						</li>
						<li class="flex items-center">
							<span class="w-2 h-2 bg-purple-500 rounded-full mr-3"></span>
							Tailwind CSS for styling
						</li>
						<li class="flex items-center">
							<span class="w-2 h-2 bg-orange-500 rounded-full mr-3"></span>
							Server-side rendering
						</li>
					</ul>
				</div>
				
				<div class="bg-white rounded-lg shadow-lg p-6">
					<h3 class="text-xl font-semibold text-gray-900 mb-4">Features</h3>
					<ul class="space-y-2 text-gray-700">
						<li class="flex items-center">
							<span class="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>
							Multi-page navigation
						</li>
						<li class="flex items-center">
							<span class="w-2 h-2 bg-green-500 rounded-full mr-3"></span>
							Responsive design
						</li>
						<li class="flex items-center">
							<span class="w-2 h-2 bg-purple-500 rounded-full mr-3"></span>
							Type-safe development
						</li>
						<li class="flex items-center">
							<span class="w-2 h-2 bg-orange-500 rounded-full mr-3"></span>
							Modern UI components
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
